---
- name: build storm reef cluster
  hosts: reef
  tasks:
  
  - name: install snap
    apt:
      name: snapd
      state: latest
      
  - name: install auditd
    apt:
      name: auditd
      state: latest
    tags: packages

  - name: install apparmor
    apt:
      name: apparmor
      state: latest
    tags: packages

  - name: install vim
    apt:
      name: vim
      state: latest
    tags: packages

  - name: install tcpdump
    apt:
      name: tcpdump
      state: latest
    tags: packages

  - name: install rsyslog
    apt:
      name: rsyslog
      state: latest
    tags: rsyslog

  - name: enable and start snapd
    shell: systemctl enable snapd && systemctl start snapd
    args:
      executable: /bin/bash
    
  - name: install microk8s snap
    shell:  yes | snap install microk8s --classic 
    args:
      executable: /bin/bash
 
  - name: apply rsyslog.conf
    copy:
      src: files/rsyslog.conf
      dest: /etc/rsyslog.conf
    tags: rsyslog
    
  - name: restart rsyslog
    shell: systemctl enable rsyslog && systemctl restart rsyslog
    args:
      executable: /bin/bash
    tags: rsyslog

  - name: add wazuh package key
    shell: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
    args:
      executable: /bin/bash
    tags: wazuh

  - name: add wazuh repo
    shell: echo "deb https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list && apt-get update
    args:
      executable: /bin/bash
    tags: wazuh

  - name: register wazuh agent
    shell: WAZUH_MANAGER="192.168.1.126" apt-get install wazuh-agent
    args:
      executable: /bin/bash
    tags: wazuh

  - name: enable wazuh agent
    shell: systemctl daemon-reload; systemctl enable wazuh-agent; systemctl start wazuh-agent
    args:
      executable: /bin/bash
    tags: wazuh


- name: use designated control-node to get tokens
  hosts: control-node
  tasks:

  - name: register control plane node add command as cadd
    shell:  microk8s add-node | head -n2 | tail -n1
    args:
      executable: /bin/bash
    register: cadd
    tags: form
 
  - name: register worker node add command as wadd
    shell:  microk8s add-node | grep worker | tail -n1
    args:
      executable: /bin/bash
    register: wadd
    tags: form

  - name: fill hostvar name
    add_host:
      name: "cnode"
      CADD: "{{ cadd.stdout }}"
      WADD: "{{ wadd.stdout }}"
    tags: form

- name: add additional control plane nodes
  hosts: added-control-plane
  tasks:

  - name: add additional control plane nodes to the cluster
    shell: "{{ hostvars['cnode']['CADD'] }}"
    args:
      executable: /bin/bash
    tags: form

- name: add worker nodes
  hosts: workers
  tasks:

  - name: add worker nodes to the cluster
    shell: "{{ hostvars['cnode']['WADD'] }}"
    args:
      executable: /bin/bash
    tags: form

- name: apply kubernetes manifests 
  hosts: control-node
  tasks:

  - name: copy out storm-network.yml to control-node
    copy:
      src: files/storm-network.yml
      dest: /root/storm-network.yml
    tags: 
      - form
      - net

  - name: copy out calicoctl patch script to control-node
    copy:
      src: files/apply-network
      dest: /root/apply-network
    tags: 
      - form
      - net

  - name: apply apply-network script
    shell: bash /root/apply-network
    args:
      executable: /bin/bash
    tags: 
      - form
      - net
